databases:
- database: school
  type: postgres
  username: postgres
  password: "123456"
  host: 129.204.121.14
  port: "5432"
  tables:
  - table: grades
    fields:
    - field: id
    - field: rank
  - table: classrooms
    fields:
    - field: id
- database: test
  type: mysql
  username: root
  password: "123456"
  host: 129.204.121.14
  port: "3306"
