databases:
- database: school
  type: postgres
  username: postgres
  password: "123456"
  host: 129.204.121.14
  port: "5432"
  tables:
  - table: classrooms
    fields:
    - field: id
  - table: grades
    fields:
    - field: id
    - field: rank
  - table: students
    fields:
    - field: name
    - field: id
- database: test
  type: mysql
  username: root
  password: "123456"
  host: 127.0.0.1
  port: "3306"
  tables:
  - table: teachers
    fields:
    - field: id
    - field: name
  - table: books
    fields:
    - field: id
    - field: name
  - table: courses
    fields:
    - field: id
    - field: name
    - field: teacher
      foreign_key: teachers
